import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/component/Layout/Layout'
import { useEffect,useContext } from 'react'

import LoginContext from '@/component/context/useContext'


export default function Home() {

  const {isLoggedIn} = useContext(LoginContext) 

  return (
    <div className='main-page'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className='home-page'>
         
          {isLoggedIn ?  <h2>Welcome To Soltelabs</h2> : <h2>Please Login to Dashboard</h2>}
        </div>
      </Layout>
    </div>
  )
}
